# Generated by Django 6.0.3 on 2026-04-11 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('pm', 'PM'), ('dev', 'Dev'), ('review', 'Review'), ('qc', 'QC')], max_length=10, unique=True)),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('starting', 'Starting'), ('ready', 'Ready'), ('processing', 'Processing'), ('error', 'Error')], default='stopped', max_length=20)),
                ('claude_session_id', models.CharField(blank=True, max_length=100)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('messages', models.JSONField(default=list)),
                ('current_activity', models.TextField(blank=True, default='')),
                ('tool_calls', models.JSONField(default=list)),
                ('event_log', models.JSONField(default=list)),
                ('total_turns', models.IntegerField(default=0)),
                ('total_cost_usd', models.FloatField(default=0.0)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_session', to='core.task')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['agent_type'], name='core_agents_agent_t_3fe9fe_idx')],
            },
        ),
    ]
