# Generated by Django 6.0.3 on 2026-04-13 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agentsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(default='')),
                ('status', models.CharField(choices=[('building', 'Building'), ('review', 'In Review'), ('iterating', 'Iterating'), ('approved', 'Approved')], default='building', max_length=20)),
                ('html_path', models.CharField(blank=True, default='', max_length=500)),
                ('backend_spec', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prototypes', to='core.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrototypeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('element_selector', models.CharField(blank=True, max_length=500)),
                ('element_text', models.CharField(blank=True, max_length=200)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.prototype')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
